spring.application.name=museu-digital
spring.datasource.url=jdbc:mysql://localhost:3306/museu_digital?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=laboratorio
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.thymeleaf.cache=false
server.port=8080
# Suprime o warning do favicon
spring.mvc.favicon.enabled=false
logging.level.org.springframework.web.servlet.resource=ERROR
